### ISSUE TITLE
Wrong Branch Preview URL for preview deployments

### ISSUE THREAD

**Issue by chalkygames123** [andykenward/github-actions-cloudflare-pages#222]
Hi,

Thank you for creating this action. It is much more promising than the official one.

I tried to deploy to a preview environment in my repository https://github.com/chalkygames123/sandbox-actions, but for some reason, the Branch Preview URL is the same as the Preview URL in both the job summary and the PR comment. Is this expected behavior, or am I misunderstanding something?

### The job summary

![CleanShot 2024-02-16 at 20 01 07](https://github.com/unlike-ltd/github-actions-cloudflare-pages/assets/5608239/5a16ee8f-cd43-4802-96be-ba31954823f6)
Source: https://github.com/chalkygames123/sandbox-actions/actions/runs/7929506470?pr=9

### The PR comment

![CleanShot 2024-02-16 at 20 16 59](https://github.com/unlike-ltd/github-actions-cloudflare-pages/assets/5608239/384e9f2d-da0b-474f-bd5b-3f0e45d5c7ba)
Source: https://github.com/chalkygames123/sandbox-actions/pull/9#issuecomment-1948167446

Additionally, it could also be a bug that the status gets stuck on "IDLE".

**Comment by andykenward** [comment]
@chalkygames123 Thank you.

You are correct about the `STATUS`. We don't wait for the status to be "success" which should then return the correct CloudFlare preview URL

The deployment status could be
```
"idle" | "active" | "canceled" | "success" | "failure" | "skipped"
```
https://github.com/unlike-ltd/github-actions-cloudflare-pages/blob/f8dd179f13510584a0fec8039046bb6c27f417a9/src/cloudflare/deployment/create.ts#L96

I remember not wanting to have a  long running GitHub Action to reduce the potential cost for all these deployments. We might have to implement either a web hook between the GitHub repository and Cloudflare pages. Or some sort of CRON or polling to the Cloudflare Pages API in an action to check for the status of success to then update the PR comments.

Will try to spend some time on this over the next couple days to see how best to fix this issue. It's been a while since I've check Cloudflare Pages API for improvements.

**Comment by andykenward** [comment]
@chalkygames123 When you get a chance try using [v1.2.0](https://github.com/unlike-ltd/github-actions-cloudflare-pages/releases/tag/v1.2.0) . Should now show the correct Preview URL.

**Comment by chalkygames123** [comment]
@andykenward Great, now it works perfectly. Thank you!
